services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="adminPasswordHere"
         - UPDATE_ON_BOOT=true
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         # - SERVER_PASSWORD="worldofpals"
         # - SERVER_NAME="World of Pals"
      volumes:
         - ./palworld:/palworld/
      labels:
         ofelia.enabled: "true"
         ofelia.job-exec.datecron.schedule: "@every 4h"
         ofelia.job-exec.datecron.command: "backup"

   ofelia:
      image: mcuadros/ofelia:latest
      depends_on:
         - palworld
      command: daemon --docker
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock:ro
